### ISSUE TITLE
Autocompletion doesn't recommend type names

### ISSUE THREAD

**Issue by DenizBasgoren** [gleam-lang/gleam#3823] opened 2024-11-12 14:46 UTC
I have a small type declared like this:

```gleam
pub type Sha3Flavor {
  Sha224
  Sha256
  Sha384
  Sha512
  Shake128(d: Int)
  Shake256(d: Int)
}
```

now I want to declare function parameters of this type like this:

```gleam
fn add_padding(input_bits: List(Bit), flavor: Sha3Flavor) -> List(Bit) {
  todo
}
```

when I write the `flavor:` part vscode extension should provide `Sha3Flavor` as a completion choice but it doesn't show it. When I write it by myself, the language server doesn't show it as an error (which is correct behavior). Language server should provide type names for completion in such cases.

**Comment by GearsDatapacks** [comment] 2024-11-12 20:56
This sounds like a duplicate of #3558

**Comment by lpil** [comment] 2024-11-12 23:38
Thank you

**Closed** 2024-11-12 23:38 UTC
