### ISSUE TITLE
Formatter removes braces erroneously

### ISSUE THREAD

**Issue by jiegillet** [gleam-lang/gleam#1923] opened 2022-12-29 12:41 UTC
Hello!
I picked up Gleam for the Advent of Code, and I really enjoy the language, so kudos to the team, thank you for developing Gleam.
I solved 18 days or so, and I ran into a few bugs, so I will be opening some issues, I hope it helps. I will also probably leave some more comments on Discord later.

-----

This one is possibly related to #1671, I'm not sure if the fix made it to 0.25.

```
$ gleam --version
gleam 0.25.0
```

The expression
```gleam
  !{ True && False}
```
gets formatted to
```gleam
  !True && False
```
which changes the value from true to false.

**Comment by lpil** [comment] 2022-12-29 17:24
Yup, you're right. This is a duplicate of that one and is fixed in v0.25.1.

Thanks for all the issues, great to have people finding ways to improve Gleam 💜

**Closed by lpil** 2022-12-29 17:24 UTC
