### ISSUE TITLE
Linux deletion error on `gleam test/run/build` etc.

### ISSUE THREAD

**Issue by BenStigsen** [gleam-lang/gleam#2680] opened 2024-03-12 12:08 UTC
**Gleam Version:** v1.0.0
**Operating System:** Fedora 39

This is what happens:
```
$ gleam new website
$ cd website
$ gleam test
  Resolving versions
Downloading packages
 Downloaded 2 packages in 0.18s
error: File IO failure

An error occurred while trying to delete this directory:

/mnt/sda1/Projects/Gleam/website/build/dev/erlang

The error message from the file IO library was:
    Directory not empty (os error 39)
```

 `sda1` is NTFS.

This was originally posted in the Discord, but I have decided to open an issue for it here. I'll update this issue within the next 3 hours and try to create a new project on my main drive.

**Comment by lpil** [comment] 2024-03-12 12:34
Oh dear! Do you know what is happening here to cause the problem? I don't have a good idea.

**Comment by Caleb-o** [comment] 2024-03-12 12:39
As I mentioned in the discord, I've had this issue as well and it seems to fail between drives. If I move the project to my main drive, then it works fine. It seems to be an odd issue with deleting across drives. I haven't tested on Windows to see if it has the same problem, but I'm running on Arch Linux.

**Comment by BenStigsen** [comment] 2024-03-12 13:37
Okay, so, it seems that am also able to perform these commands on the main drive, which is `btrfs`.

**Comment by MedLabs** [comment] 2024-03-29 05:17
I have exactly the same issue, using linux and trying this on a NTFS partition

**Comment by lpil** [comment] 2024-03-29 10:40
Closing this to use the other issue to track

**Closed by lpil** 2024-03-29 10:40 UTC
Labels: bug, help wanted, priority:high

**Comment by srackham** [comment] 2024-11-01 02:34
I have the same issue on both NixOS and Manjaro Linux.

To reproduce the error create and run a new project on a Linux NFS mount.

- Environments: NixOS 24.05 running gleam 1.4.1 and on Manjaro Linux running gleam 1.5.1.
- NFS mount:

      nuc1:/srackham on /home/srackham/share type nfs4 (rw,relatime,vers=4.2,rsize=524288,wsize=524288,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,clientaddr=192.168.1.125,local_lock=none,addr=192.168.1.243)

To reproduce the error:
    
```
$ gleam --version
gleam 1.4.1

$ gleam new vars
Your Gleam project vars has been successfully created.
The project can be compiled and tested by running these commands:

        cd vars
        gleam test


$ cd vars

$ gleam run
  Resolving versions
Downloading packages
 Downloaded 2 packages in 1.01s
error: File IO failure

An error occurred while trying to delete this directory:

    /home/srackham/share/projects/gleam/vars/build/dev/erlang

The error message from the file IO library was:

    Directory not empty (os error 39)

$ ls -a /home/srackham/share/projects/gleam/vars/build/dev/erlang
```

Note that although the error reports that the directory was not empty, it is empty after the command exits.
