### ISSUE TITLE
Option to suppress gleam cli's log messages

### ISSUE THREAD

**Issue by isaacthefallenapple** [gleam-lang/gleam#3309] opened 2024-06-22 08:51 UTC
It's often useful to be able to pipe a programs standard output into another program. Unfortunately, the `gleam run` command prints its log messages (like `Compiled in 0.2 seconds`, `Running program.main`, etc.) to standard output unconditionally making this annoying, particularly because the number of lines of log messages vary depending on whether the build was cached or not.

This would be (I hope) easily fixed by adding a `-q/--quiet` option to the cli to suppress the log messages wholesale and/or print them to stderr (as is quite common in most build tools, I think) to allow the user to redirect them wherever.

**Comment by lpil** [comment] 2024-06-22 14:54
Thank you.

Duplicate of https://github.com/gleam-lang/gleam/issues/2299

**Closed by lpil** 2024-06-22 14:54 UTC
