### ISSUE TITLE
Invalid TypeScript definitions when importing type alias

### ISSUE THREAD

**Issue by richard-viney** [gleam-lang/gleam#3664] opened 2024-10-03 01:09 UTC
This code:

```gleam
// my_dict.gleam

import gleam/dict.{type Dict}

pub type MyDict =
  Dict(String, String)
```

```gleam
// my_lib.gleam

import my_dict.{type MyDict}

pub fn go(d: MyDict) {
  todo
}
```

Generates this `.d.ts` file:

```ts
import type * as $my_dict from "./my_dict.d.mts";

export function go(d: $dict.Dict$<string, string>): undefined;
```

Which is invalid due to the unknown `$dict` reference.

It should probably generate this instead:

```ts
import type * as $my_dict from "./my_dict.d.mts";

export function go(d: $my_dict.MyDict): undefined;
```

**Comment by GearsDatapacks** [comment] 2024-10-03 12:04
I believe this is a duplicate of #2315

**Comment by richard-viney** [comment] 2024-10-03 20:40
Yes sorry it does look like a duplicate.

**Closed** 2024-10-03 20:40 UTC
Labels: bug
