### ISSUE TITLE
Language server fails to report error when a module is renamed/removed

### ISSUE THREAD

**Issue by GearsDatapacks** [gleam-lang/gleam#3409] opened 2024-07-17 18:49 UTC
When you rename a module referenced by another module, the Gleam language server still thinks that the original module name exists.

Steps to reproduce:
- Create two files: `main.gleam` and `mod.gleam`
- In `main.gleam` add the following import:
  ```gleam
  import mod
  ```
- Rename `mod.gleam` to anything else, like `mod2.gleam`
- The Language Server doesn't report any errors in `main.gleam`, even though `mod.gleam` no longer exists

Gleam version: Latest nightly
OS: Ubuntu 24.04

**Note**: This does not affect the compiler in any way, only the language server. Probably low priority

**Comment by lpil** [comment] 2024-07-18 12:11
Duplicate of https://github.com/gleam-lang/gleam/issues/1970

**Closed by lpil** 2024-07-18 12:11 UTC
Labels: bug
