### ISSUE TITLE
List pattern matching

### ISSUE THREAD

**Issue by giacomocavalieri** [gleam-lang/gleam#3108] opened 2024-05-07 14:59 UTC
There's a strange pattern that I don't think should compile when pattern matching on a list:
```gleam
case list {
  [first..rest] -> todo
//^^^^^^^^^^^^^ This compiles as [first, ..rest]
  _ -> todo
}
```
I think it should be a parse error instead

**Comment by zanddev** [comment] 2024-05-07 15:18
@giacomocavalieri This is a duplicate of #3107, but this issue is written better than mine.

**Comment by lpil** [comment] 2024-05-07 19:07
It would be a breaking change to make this an error, but we could emit a warning.

**Comment by giacomocavalieri** [comment] 2024-05-07 19:58
Oh right that's unfortunate, I'll work on adding the warning then!

**Comment by lpil** [comment] 2024-05-07 20:06
Thank you

**Comment by giacomocavalieri** [comment] 2024-05-21 07:53
I was wondering, what would the warning say? Does it even make sense to have a warning to suggest a different way of writing it even if the formatter already takes care of it?

Something like this, maybe?
```
  [a..b]
  ^^^^^^

This is the same as writing `[a, ..b]`
```

**Comment by lpil** [comment] 2024-05-21 12:19
Maybe we could say that the syntax is deprecated?

**Closed** 2024-06-22 15:36 UTC
Labels: help wanted, good first issue, priority:medium
