### ISSUE TITLE
Skip optional dependencies

### ISSUE THREAD

**Issue by gusinacio** [gleam-lang/gleam#3555] opened 2024-08-22 14:23 UTC
Elixir packages allows to mark a dependency as optional, which reduces compile time and also allows you to select better runtime support, algorithms and additional features.

Currently, [`rustler`](https://github.com/rusterlium/rustler/tree/master) (an FFI package between Rust and Erlang) compiles the packages with `rustler` as an optional dependency in case you don't want to use the prebuilt binaries.

Rustler is currently one of the most important packages for FFI with Erlang and it's crucial that Gleam supports it well.
By skipping the compilation of the optional dependencies and letting the users add the optional dependency by themselves, rustler is supported without effort.

**Comment by lpil** [comment] 2024-08-23 15:17
Thank you. Duplicate of https://github.com/gleam-lang/gleam/issues/1964

**Closed by lpil** 2024-08-23 15:17 UTC
Labels: bug
