### ISSUE TITLE
Invalid warning about unused module alias

### ISSUE THREAD

**Issue by Nicd** [gleam-lang/gleam#2621] opened 2024-02-27 14:18 UTC
This line produces a compile warning on 0.34.1: https://gitlab.com/Nicd/elektrofoni/-/blob/9f1af761e5f095fbb48d37e1a1e6f501a1a8e7ff/src/elekf/web/authed_view.gleam#L29

```
warning: Unused imported module alias
   ┌─ /Users/nicd/svn/elektrofoni/src/elekf/web/authed_view.gleam:29:44
   │
29 │ import elekf/web/components/player/actions as player_actions
   │                                            ^^^^^^^^^^^^^^^^^ This imported module alias is never used

Hint: You can safely remove it.
```

But as you can see later in the file, that module alias _is_ used. E.g. on this line: https://gitlab.com/Nicd/elektrofoni/-/blob/9f1af761e5f095fbb48d37e1a1e6f501a1a8e7ff/src/elekf/web/authed_view.gleam#L161

Sorry, I don't know of a minification of this problem.

**Comment by Nicd** [comment] 2024-02-27 14:25
I get the same on 1.0.0-rc2 also.

**Comment by lpil** [comment] 2024-02-27 14:36
Thanks! Duplicate of this https://github.com/gleam-lang/gleam/issues/2579

**Closed by lpil** 2024-02-27 14:36 UTC
