### ISSUE TITLE
Field accesses fail on `as` patterns for records with multiple variants

### ISSUE THREAD

**Issue by QuinnWilton** [gleam-lang/gleam#735] opened 2020-07-16 06:56 UTC
I'm not positive if this is a bug or not, but I ran into it while working on #722. The following code fails to compile on `main`:

```gleam
pub type Either(a, b) {
    Left(value: a)
    Right(value: b)
};

pub fn main() {
  case Left(5) {
    Left(_) as l -> {
      l.value
    }
  }
}
```

With the error:

```
error: Unknown field
   ââ /Users/wilton/dev/gleam_experiments/src/gleam_experiments.gleam:13:8
   â
13 â       l.value
   â        ^^^^^^ This field does not exist

The value has this type:

    Either(Int, a)

It does not have any fields.
```

It's possible that this is a duplicate of #685, but I was a little surprised that this didn't work.

**Comment by lpil** [comment] 2020-07-16 08:58
Aye, this is a duplicate of the other issue. Gleam doesn't know how to specialise a custom type to just one of its variants in a case expression. I'll close this so we can keep track in the other issue.

**Closed by lpil** 2020-07-16 08:58 UTC
