### ISSUE TITLE
Unclear JavaScript FFI Requirements & Qwirks

### ISSUE THREAD

**Issue by daniellionel01** [gleam-lang/gleam#3926] opened 2024-12-01 14:18 UTC
It seems that there are some nuances around the JavaScript FFI usage in Gleam that I am not aware of. It seems that I can import JavaScript files that are located directly in the `src` directory just fine, but importing them from anywhere else yields an error that it cannot find the file. I cannot find documentation on if this is normal or if there is any other configuration / convention I am not aware of.

It would be pretty cool if I could import files from anywhere and it would just copy those files into the build directory.

Here is a small repository that demonstrates my issue: https://github.com/daniellionel01/gleam_js_ffi

- Gleam Version: `gleam 1.6.2`
- OS: `Darwin MacBook 24.0.0 Darwin Kernel Version 24.0.0 (macOS 15.0.1)`

**Comment by lpil** [comment] 2024-12-01 14:27
Thanks! Duplicate of https://github.com/gleam-lang/gleam/issues/1562

**Closed by lpil** 2024-12-01 14:27 UTC
Labels: bug

**Comment by daniellionel01** [comment] 2024-12-01 14:28
Ah got'u! Thank you!
