### ISSUE TITLE
LSP Code action: Add type annotations

### ISSUE THREAD

**Issue by XeroOl** [gleam-lang/gleam#3536] opened 2024-08-19 19:24 UTC
Sometimes, I write functions without putting in an explicit return type, but it would be good to be able to add it on later:
```gleam
fn my_function(x: Int) {
  #(x + 1, x + 2)
}
```
->
```gleam
fn my_function(x: Int) -> Int {
    #(x + 1, x + 2)
}
```

Ideally, it would be possible to infer types on:
* function arguments
* function return values
* let expressions
* use expressions
and possibly more places.

I think this is related to, but distinct from inlay hints.

**Comment by giacomocavalieri** [comment] 2024-08-19 19:31
Hello! I think this is a duplicate of https://github.com/gleam-lang/gleam/issues/2954

**Comment by XeroOl** [comment] 2024-08-19 19:53
ahh, good point. Apologies for the duplicate

**Closed** 2024-08-19 19:53 UTC
