### ISSUE TITLE
Compiler fatal crash when defining a type with the same name as an imported type.

### ISSUE THREAD

**Issue by schurhammer** [gleam-lang/gleam#3209] opened 2024-05-29 10:42 UTC
```gleam
import wisp.{type Request}
type Request { Request }
```

Defining a duplicate type name like this causes a fatal compiler crash.

```
Panic: compiler-core/src/analyse.rs:991
        name uniqueness checked above: DuplicateTypeName { location: SrcSpan { start: 233, end: 245 }, previous_location: SrcSpan { start: 203, end: 215 }, name: "Request" }
Gleam version: 1.2.0-nightly-20240528
Operating system: linux
        ```

**Comment by lpil** [comment] 2024-05-29 10:46
Thank you

**Comment by hesampakdaman** [comment] 2024-05-29 19:24
Looked through the code and [found this `expect` statement](https://github.com/gleam-lang/gleam/blob/c2a6660134db8b72f4b398df7a82e5a9e393d25d/compiler-core/src/analyse.rs#L991). Would we like to bubble of some type of error here instead?

**Comment by PgBiel** [comment] 2024-06-09 02:00
Can reproduce on Gleam 1.2.1.

The code below also triggers the problem:

```gleam
import gleam/dynamic.{type Dynamic}

pub type Dynamic

pub fn main() {
  io.println("Hello from totgus!")
}
```

**Comment by GearsDatapacks** [comment] 2024-06-10 22:02
The problem comes because when imported types are defined, they don't register them in the same map which gets checked in `assert_unique_type_name`, so that function doesn't realise they exist and causes the crash. 
Namely, this is the `type_names` field of `ModuleAnalyzer`, which the `Importer` code doesn't have access to. Is there any reason this should be separate to `Environments`'s `module_types`?

**Closed** 2024-06-12 12:01 UTC
Labels: bug, help wanted, good first issue, priority:high
