### ISSUE TITLE
Formatter moves comments out of their scope

### ISSUE THREAD

**Issue by digitalcora** [gleam-lang/gleam#2196] opened 2023-05-30 15:58 UTC
Just encountered a minor `gleam format` anomaly:

```gleam
fn(arg) {
  // I'm free!
}
```

⬇️

```gleam
fn(arg) { todo }
// I'm free!
```

The comment "escapes" from the function body. This also happens if the anonymous function is being given as an argument to a function; then the comment is moved out of the call entirely, onto the next line after the call.

**Comment by lpil** [comment] 2023-05-30 16:00
Thank you

**Comment by digitalcora** [comment] 2023-05-30 17:03
Found another one, dramatic example:

```gleam
case True {
  True ->
    case False {
      False ->
        case True {
          True -> True
          _ -> panic // I'm free!
        }
    }
}
```

⬇️ 

```gleam
case True {
  True ->
    case False {
      False ->
        case True {
          True -> True
          _ -> panic
        }
    }
}

// I'm free!
```

**Comment by ianjkaplan** [comment] 2023-08-22 22:16
Hi!

Im new around here but would Im really enjoying playing with gleam, writing rust and learning about all kinds languages! (but strongly typed functional languages are clearly the best) 

This issue came up as I started playing with the language because occasionally like to write comments on the same line as a variable. The gleam book also references same line comments.  I figured it would be a great starting point to jump in and take a look around and learn some things in the process. so here it goes...


Though I do not get the same behavior @digitalcora  describes running gleam 0.30.5, I found some similar examples.

**custom type definitions**

```gleam
pub type MyType {
  Thing // I'm free!
}
```
⬇️ 

```gleam
pub type MyType {
  Thing
}
// I'm free!
```

if we have two custom type definition the comment jumps an extra line.
```gleam
pub type MyType {
  Thing // freedom!
}

pub type MyOtherType {
  OtherThing
}

```
⬇️ 

```gleam
pub type MyType {
  Thing
}

// freedom!

pub type MyOtherType {
  OtherThing
}

```

When two custom type definitions are adjacent the comment skips a line after the closing bracket.

**case statements**

```gleam
  case True {
    True -> 1 //  Almost Escaped!
    _ -> 0
  }
```
⬇️ 
```gleam
  case True {
    True -> 1 
   // Almost Escaped!
    _ -> 0
  }
```

```gleam
  case True {
    True -> 1
    _ -> 0 // Escaped!
  }
```
⬇️ 
```gleam
  case True {
    True -> 1 
    _ -> 0
  }
// Escaped!
```

**expression blocks**
```gleam
  let val: Bool = {
    False // time to fly!
  }
```
⬇️ 
```gleam
  let val: Bool = {
    False 
  }
// time to fly!
```
**expression blocks**
```gleam
  let val: Bool = {
     "Side effect!" // Oops wrong line!
    True
  }
```
⬇️ 
```gleam
  let val: Bool = {
   "Side effect!"
   // Oops wrong line!
    True 
  }
```
An same line comment on a field other than the last field in a custom expression block or type definition is formatted as it is associated with the field below, at least thats how I would read it.

I started poking around the compiler and found some behavior that at least partially explains, if not already well understood by the core team.

I dug into the custom type example first and noticed that the `gleam_core::format::Formatter::custom_type` creates a `Document` that does not include the comment when the comment is on the same line as the field. This is because `format::Formatter::pop_comments` is provided a byte-index corresponding to the start index of the field, before the start of the comment, which is intended behavior according to the doc comment on `gleam_core::format::Formatter::pop_comments`.

```rust
    /// Pop comments that occur before a byte-index in the source, consuming
    /// and retaining any empty lines contained within.
    fn pop_comments(&mut self, limit: u32) -> impl Iterator<Item = Option<&'comments str>> {
        let (popped, rest, empty_lines) =
            comments_before(self.comments, self.empty_lines, limit, true);
        self.comments = rest;
        println!("rest comments {:?}", rest);
        self.empty_lines = empty_lines;
        popped
    }
```


`gleam_core::format::Formatter::module` grabs the comments remaining and pushes them outside of the scope when constructing the final `Document`. 

When there are multiple fields the next field "captures" the comment on the previous line so it is formatted to be above the next line. this does not seem like the desired behavior according to the gleam book and it seems surprising to me. 

My takeaway from the gleam book is that same line comments like the examples above should remain on the same line when formatted, not on the line above the commented syntax. Is this correct @lpil?  

 I'm happy to open a PR with some explicit handling of same line comments/ comments before the termination of a scope. Id appreciate some feedback and any additional thoughts/ tips before I move in that direction.

If someone is actively working on this and wants to pick it up that's awesome too!

**Comment by lpil** [comment] 2023-08-25 09:48
Hey!

> My takeaway from the gleam book is that same line comments like the examples above should remain on the same line when formatted, not on the line above the commented syntax. Is this correct @lpil?

The formatter doesn't support trailing comments, so adding that would be a new feature rather than a bug fix.

For example, this:

```gleam
1 // abc
2
```
is expected to format to this
```gleam
1
// abc
2
```

> I'm happy to open a PR with some explicit handling of same line comments/ comments before the termination of a scope. Id appreciate some feedback and any additional thoughts/ tips before I move in that direction.

Amazing, thank you. This is exactly what needs to be done for this bug. 💜

**Comment by lpil** [comment] 2023-10-17 13:26
Do you still want to work on this @ianjkaplan ?

**Comment by ianjkaplan** [comment] 2023-10-17 15:29
yes! Got busy with some other things unless there is already work on this front?

**Comment by lpil** [comment] 2023-10-18 10:23
No problem, I'll hold off then :)

**Comment by lpil** [comment] 2023-11-08 15:00
I've done a few tests and I'm not sure what work is still to do here. Is this done?

**Comment by ianjkaplan** [comment] 2023-11-08 15:27
yeah this actually looks good ive been playing around with it and i dont have anything better to add actually

**Comment by lpil** [comment] 2023-11-09 14:57
Thank you

**Closed by lpil** 2023-11-09 14:57 UTC
Labels: bug, help wanted, good first issue, priority:medium
