### ISSUE TITLE
Fix VS Code duplicating module name when autocompleting module functions

### ISSUE THREAD

**Issue by VlkrS** [gleam-lang/gleam#2165] opened 2023-05-24 09:12 UTC
When testing autocomplete with helix (helix-editor.com), I get some odd behavior:

Entering 

``string.re`` doesn't give me an autocompletion but a live error message ``the module gleam/string does not have a re field.

When completing ``string.repeat``, I get offered an autocompletion, which - when accepted, expands to ``string.string.repeat``.

When not accepting, but deleting characters back to ``string.rep``, I get an autocompletion offered for ``string.replace``, ``string.repeat``, ... (including ``string.is_empty``, which doesn't look like a good match).

However the gist of it is that I need to first completely type a valid field in a module in order to make autocompletion yield anything on that line of code.

**Comment by lpil** [comment] 2023-05-24 09:27
This due to unfortunate ambiguity in the LSP specification. The manner in which autocompletions are inserted by the client is "open to interpretation". In future we will use the more complex autocompletion API in order to ensure no editors do this, but it has not yet been implemented.

**Comment by VlkrS** [comment] 2023-05-24 09:37
I understand that this explains why ``string.replace`` turns into ``string.string.replace`` when completed, correct?
But that no autocompletion is found before a complete symbol is entered should not be affected by this, right?

**Comment by lpil** [comment] 2023-05-24 09:39
I think it's that this editor is using `.` as the input boundary. I was hoping they'd instead match the whole prefix, but alas it seems not to be the case.

**Comment by lpil** [comment] 2023-05-24 19:04
Oh I see, I didn't realise you were reporting two problem. Could you open a second one with code examples for how the problem is triggered? Thank you.

**Comment by Acepie** [comment] 2024-06-01 01:06
Can you assign this to me? I started on this as part of improving https://github.com/gleam-lang/gleam/pull/3219 I was originally going to implement a filter such that we look at the last name including the dot before the cursor and realized that we could/should use the same mechanism for solving this problem/improving completion filtering in general. I got something working locally that I like but need to write up some tests/refactor a bit. I'll probably put up a draft pr either later tonight or over the weekend but it would build on top of the other pr.

**Comment by Acepie** [comment] 2024-06-01 04:37
I have something that feels good to use locally but I'm not quite happy with the code yet https://github.com/Acepie/gleam/pull/1 I'm gonna leave this here and think about it more later.

**Closed** 2024-06-17 09:14 UTC
Labels: bug, help wanted, priority:high
