### ISSUE TITLE
LSP import autocompletion fails to trigger

### ISSUE THREAD

**Issue by rawhat** [gleam-lang/gleam#1703] opened 2022-07-26 17:55 UTC
The example posted in the Discord showed `gleam_erlang` displaying autocompletion in the `file` module.  I can confirm that this works in that sub-module.

Using [mist](https://github.com/rawhat/mist), I get suggestions in the main `src/mist.gleam` module.  However, in any submodule, i.e. `src/mist/file.gleam`, I don't get any.  It behaves similarly for `glisten`.

If I create a new project with `gleam new lsp_test`, I do not get any autocompletion suggestions, even in the `src/lsp_test.gleam` module for `gleam_stdlib`.

This is being run with `cargo build --release` on the latest `main` branch.  This behavior is identical in both neovim and VSCode.

I added some logging for my neovim LSP, and I can see that for the "working" modules, it does receive an rpc response:

```
[DEBUG][2022-07-25 17:39:48] .../vim/lsp/rpc.lua:364    "rpc.send"    {  id = 3,  jsonrpc = "2.0",  method = "textDocument/completion",  params = {    context = {      triggerCharacter = " ",      triggerKind = 2    },    position = {      character = 7,      line = 3    },    textDocument = {      uri = "file:///home/alex/gleams/mist/src/mist.gleam"    }  }}
// truncated cause it's the full response
```

However, the ones that do not work seem to get some kind of incomplete response:

```
[DEBUG][2022-07-25 17:40:45] .../vim/lsp/rpc.lua:364    "rpc.send"    {  id = 3,  jsonrpc = "2.0",  method = "textDocument/completion",  params = {    context = {      triggerCharacter = " ",      triggerKind = 2    },    position = {      character = 7,      line = 14    },    textDocument = {      uri = "file:///home/alex/elixirs/spades/src/spades.gleam"    }  }}
[DEBUG][2022-07-25 17:40:45] .../vim/lsp/rpc.lua:473    "rpc.receive"    {  id = 3,  jsonrpc = "2.0"}
```

Happy to provide any more info, if it's helpful!

**Comment by lpil** [comment] 2022-07-27 17:40
Thank you

**Comment by lucasavila00** [comment] 2022-08-22 19:47
I'm able to reproduce. I'll take a look at it.

**Comment by lucasavila00** [comment] 2022-08-22 21:09
The issue is that VSCode / language client is not sending the `textDocument/completion` message to the language server.

I'm trying to figure out why...

**Comment by lucasavila00** [comment] 2022-08-22 21:32
mist.gleam works because of the docs

```gleam
import gleam/io

/// now it will work
/// now it will work
/// now it will work
/// now it will work
/// now it will work
/// now it will work
/// now it will work
pub fn a() {
  io.debug("a")
}
```

**Comment by lucasavila00** [comment] 2022-08-22 21:41
The underlying issue is that `textDocument/didChange` events are not stored and used for the auto-completion part.

Or, in other words, that the auto-completion part does not use the in-memory text.

**Comment by lpil** [comment] 2022-08-26 10:44
We could move the import autocompletion over to use the latest but as-yet untyped source, like the formatter does. This would work as we don't need type information to know what modules exist, yet it would give us accurate information about whether the cursor is within a statement or not.

**Comment by lpil** [comment] 2022-08-27 17:49
I have improved the autocompletion to a degree where I think we can close this. Further improvements will come with partial compilation.

**Closed by lpil** 2022-08-27 17:50 UTC
Labels: bug, help wanted, area:tooling
