### ISSUE TITLE
Detect unused variables in recursive function

### ISSUE THREAD

**Issue by giacomocavalieri** [gleam-lang/gleam#3812] opened 2024-11-10 17:00 UTC
It would be cool if the compiler could detect an unused variable in a recursive function when the variable is never actually used but only passed to the recursive call. For example:
```gleam
pub fn loop(cond: Bool, unused: Int) {
  case cond {
    True -> loop(False, unused)
    False -> 1
  }
}
```
Here `unused` is only ever passed to the recursive call but never actually used. Example of a bug that could have been prevented by this: <https://github.com/gleam-lang/otp/pull/84#discussion_r1835737065>

**Comment by lpil** [comment] 2024-11-10 17:58
Thank you. Duplicate of https://github.com/gleam-lang/gleam/issues/2634

Can make sure we have a test for it in there.

**Closed by lpil** 2024-11-10 17:58 UTC

**Comment by giacomocavalieri** [comment] 2024-11-10 18:43
Oops sorry for the noise! And I was the author of that issue as well! 😅
