### ISSUE TITLE
Quiet flag for `gleam run`

### ISSUE THREAD

**Issue by dmodena** [gleam-lang/gleam#2883] opened 2024-04-02 08:00 UTC
Could we have a `-q | --quiet` flag for `gleam run`?

I recently found out about Gleam and got enthusiastic about it. I completed the language tour and decided to give it a try.

After installing on Mac using homebrew (which was super convenient, btw) I followed the [tutorial](https://gleam.run/writing-gleam/) by creating a new project and running it with `gleam run`. Then I got the following output:

```
  **Compiling** gleam_stdlib
  **Compiling** gleeunit
  **Compiling** hello
   **Compiled** in 1.38s
    **Running** hello.main
Hello from hello!
```

I thought it made sense to have the compiling status printed, but I wanted to just see the "Hello from hello!" on my terminal, so I decided to try with a `--quiet` flag to see if I would get that, but it doesn't exist.

Could we have a quiet mode for this scenario?

**Comment by lpil** [comment] 2024-04-02 10:07
Yup! Duplicate of https://github.com/gleam-lang/gleam/issues/2299

**Closed** 2024-04-02 10:07 UTC
